#!/bin/bash

mv ADAMS\ FVE\ $1.txt            ADAMS_FVE_$1.txt
mv ALLEGHENY\ FVE\ $1.txt        ALLEGHENY_FVE_$1.txt
mv ARMSTRONG\ FVE\ $1.txt        ARMSTRONG_FVE_$1.txt
mv BEAVER\ FVE\ $1.txt           BEAVER_FVE_$1.txt
mv BEDFORD\ FVE\ $1.txt          BEDFORD_FVE_$1.txt
mv BERKS\ FVE\ $1.txt            BERKS_FVE_$1.txt
mv BLAIR\ FVE\ $1.txt            BLAIR_FVE_$1.txt
mv BRADFORD\ FVE\ $1.txt         BRADFORD_FVE_$1.txt
mv BUCKS\ FVE\ $1.txt            BUCKS_FVE_$1.txt
mv BUTLER\ FVE\ $1.txt           BUTLER_FVE_$1.txt
mv CAMBRIA\ FVE\ $1.txt          CAMBRIA_FVE_$1.txt
mv CAMERON\ FVE\ $1.txt          CAMERON_FVE_$1.txt
mv CARBON\ FVE\ $1.txt           CARBON_FVE_$1.txt
mv CENTRE\ FVE\ $1.txt           CENTRE_FVE_$1.txt
mv CHESTER\ FVE\ $1.txt          CHESTER_FVE_$1.txt
mv CLARION\ FVE\ $1.txt          CLARION_FVE_$1.txt
mv CLEARFIELD\ FVE\ $1.txt       CLEARFIELD_FVE_$1.txt
mv CLINTON\ FVE\ $1.txt          CLINTON_FVE_$1.txt
mv COLUMBIA\ FVE\ $1.txt         COLUMBIA_FVE_$1.txt
mv CRAWFORD\ FVE\ $1.txt         CRAWFORD_FVE_$1.txt
mv CUMBERLAND\ FVE\ $1.txt       CUMBERLAND_FVE_$1.txt
mv DAUPHIN\ FVE\ $1.txt          DAUPHIN_FVE_$1.txt
mv DELAWARE\ FVE\ $1.txt         DELAWARE_FVE_$1.txt
mv ELK\ FVE\ $1.txt              ELK_FVE_$1.txt
mv ERIE\ FVE\ $1.txt             ERIE_FVE_$1.txt
mv FAYETTE\ FVE\ $1.txt          FAYETTE_FVE_$1.txt
mv FOREST\ FVE\ $1.txt           FOREST_FVE_$1.txt
mv FRANKLIN\ FVE\ $1.txt         FRANKLIN_FVE_$1.txt
mv FULTON\ FVE\ $1.txt           FULTON_FVE_$1.txt
mv GREENE\ FVE\ $1.txt           GREENE_FVE_$1.txt
mv HUNTINGDON\ FVE\ $1.txt       HUNTINGDON_FVE_$1.txt
mv INDIANA\ FVE\ $1.txt          INDIANA_FVE_$1.txt
mv JEFFERSON\ FVE\ $1.txt        JEFFERSON_FVE_$1.txt
mv JUNIATA\ FVE\ $1.txt          JUNIATA_FVE_$1.txt
mv LACKAWANNA\ FVE\ $1.txt       LACKAWANNA_FVE_$1.txt
mv LANCASTER\ FVE\ $1.txt        LANCASTER_FVE_$1.txt
mv LAWRENCE\ FVE\ $1.txt         LAWRENCE_FVE_$1.txt
mv LEBANON\ FVE\ $1.txt          LEBANON_FVE_$1.txt
mv LEHIGH\ FVE\ $1.txt           LEHIGH_FVE_$1.txt
mv LUZERNE\ FVE\ $1.txt          LUZERNE_FVE_$1.txt
mv LYCOMING\ FVE\ $1.txt         LYCOMING_FVE_$1.txt
mv McKEAN\ FVE\ $1.txt           McKEAN_FVE_$1.txt
mv MERCER\ FVE\ $1.txt           MERCER_FVE_$1.txt
mv MIFFLIN\ FVE\ $1.txt          MIFFLIN_FVE_$1.txt
mv MONROE\ FVE\ $1.txt           MONROE_FVE_$1.txt
mv MONTGOMERY\ FVE\ $1.txt       MONTGOMERY_FVE_$1.txt
mv MONTOUR\ FVE\ $1.txt          MONTOUR_FVE_$1.txt
mv NORTHAMPTON\ FVE\ $1.txt      NORTHAMPTON_FVE_$1.txt
mv NORTHUMBERLAND\ FVE\ $1.txt   NORTHUMBERLAND_FVE_$1.txt
mv PERRY\ FVE\ $1.txt            PERRY_FVE_$1.txt
mv PHILADELPHIA\ FVE\ $1.txt     PHILADELPHIA_FVE_$1.txt
mv PIKE\ FVE\ $1.txt             PIKE_FVE_$1.txt
mv POTTER\ FVE\ $1.txt           POTTER_FVE_$1.txt
mv SCHUYLKILL\ FVE\ $1.txt       SCHUYLKILL_FVE_$1.txt
mv SNYDER\ FVE\ $1.txt           SNYDER_FVE_$1.txt
mv SOMERSET\ FVE\ $1.txt         SOMERSET_FVE_$1.txt
mv SULLIVAN\ FVE\ $1.txt         SULLIVAN_FVE_$1.txt
mv SUSQUEHANNA\ FVE\ $1.txt      SUSQUEHANNA_FVE_$1.txt
mv TIOGA\ FVE\ $1.txt            TIOGA_FVE_$1.txt
mv UNION\ FVE\ $1.txt            UNION_FVE_$1.txt
mv VENANGO\ FVE\ $1.txt          VENANGO_FVE_$1.txt
mv WARREN\ FVE\ $1.txt           WARREN_FVE_$1.txt
mv WASHINGTON\ FVE\ $1.txt       WASHINGTON_FVE_$1.txt
mv WAYNE\ FVE\ $1.txt            WAYNE_FVE_$1.txt
mv WESTMORELAND\ FVE\ $1.txt     WESTMORELAND_FVE_$1.txt
mv WYOMING\ FVE\ $1.txt          WYOMING_FVE_$1.txt
mv YORK\ FVE\ $1.txt             YORK_FVE_$1.txt