# input filename is $1
# output files are COUNTYNAME_$1

grep 'ADAMS'                       $1 > 'ADAMS_'$1
grep 'ALLEGHENY'                   $1 > 'ALLEGHENY_'$1
grep 'ARMSTRONG'                   $1 > 'ARMSTRONG_'$1
grep 'BEAVER'                      $1 > 'BEAVER_'$1
grep 'BEDFORD'                     $1 > 'BEDFORD_'$1
grep 'BERKS'                       $1 > 'BERKS_'$1
grep 'BLAIR'                       $1 > 'BLAIR_'$1
grep 'BRADFORD'                    $1 > 'BRADFORD_'$1
grep 'BUCKS'                       $1 > 'BUCKS_'$1
grep 'BUTLER'                      $1 > 'BUTLER_'$1
grep 'CAMBRIA'                     $1 > 'CAMBRIA_'$1
grep 'CAMERON'                     $1 > 'CAMERON_'$1
grep 'CARBON'                      $1 > 'CARBON_'$1
grep 'CENTRE'                      $1 > 'CENTRE_'$1
grep 'CHESTER'                     $1 > 'CHESTER_'$1
grep 'CLARION'                     $1 > 'CLARION_'$1
grep 'CLEARFIELD'                  $1 > 'CLEARFIELD_'$1
grep 'CLINTON'                     $1 > 'CLINTON_'$1
grep 'COLUMBIA'                    $1 > 'COLUMBIA_'$1
grep 'CRAWFORD'                    $1 > 'CRAWFORD_'$1
grep 'CUMBERLAND'                  $1 > 'CUMBERLAND_'$1
grep 'DAUPHIN'                     $1 > 'DAUPHIN_'$1
grep 'DELAWARE'                    $1 > 'DELAWARE_'$1
grep 'ELK'                         $1 > 'ELK_'$1
grep 'ERIE'                        $1 > 'ERIE_'$1
grep 'FAYETTE'                     $1 > 'FAYETTE_'$1
grep 'FOREST'                      $1 > 'FOREST_'$1
grep 'FRANKLIN'                    $1 > 'FRANKLIN_'$1
grep 'FULTON'                      $1 > 'FULTON_'$1
grep 'GREENE'                      $1 > 'GREENE_'$1
grep 'HUNTINGDON'                  $1 > 'HUNTINGDON_'$1
grep 'INDIANA'                     $1 > 'INDIANA_'$1
grep 'JEFFERSON'                   $1 > 'JEFFERSON_'$1
grep 'JUNIATA'                     $1 > 'JUNIATA_'$1
grep 'LACKAWANNA'                  $1 > 'LACKAWANNA_'$1
grep 'LANCASTER'                   $1 > 'LANCASTER_'$1
grep 'LAWRENCE'                    $1 > 'LAWRENCE_'$1
grep 'LEBANON'                     $1 > 'LEBANON_'$1
grep 'LEHIGH'                      $1 > 'LEHIGH_'$1
grep 'LUZERNE'                     $1 > 'LUZERNE_'$1
grep 'LYCOMING'                    $1 > 'LYCOMING_'$1
grep 'McKEAN'                      $1 > 'McKEAN_'$1
grep 'MERCER'                      $1 > 'MERCER_'$1
grep 'MIFFLIN'                     $1 > 'MIFFLIN_'$1
grep 'MONROE'                      $1 > 'MONROE_'$1
grep 'MONTGOMERY'                  $1 > 'MONTGOMERY_'$1
grep 'MONTOUR'                     $1 > 'MONTOUR_'$1
grep 'NORTHAMPTON'                 $1 > 'NORTHAMPTON_'$1
grep 'NORTHUMBERLAND'              $1 > 'NORTHUMBERLAND_'$1
grep 'PERRY'                       $1 > 'PERRY_'$1
grep 'PHILADELPHIA'                $1 > 'PHILADELPHIA_'$1
grep 'PIKE'                        $1 > 'PIKE_'$1
grep 'POTTER'                      $1 > 'POTTER_'$1
grep 'SCHUYLKILL'                  $1 > 'SCHUYLKILL_'$1
grep 'SNYDER'                      $1 > 'SNYDER_'$1
grep 'SOMERSET'                    $1 > 'SOMERSET_'$1
grep 'SULLIVAN'                    $1 > 'SULLIVAN_'$1
grep 'SUSQUEHANNA'                 $1 > 'SUSQUEHANNA_'$1
grep 'TIOGA'                       $1 > 'TIOGA_'$1
grep 'UNION'                       $1 > 'UNION_'$1
grep 'VENANGO'                     $1 > 'VENANGO_'$1
grep 'WARREN'                      $1 > 'WARREN_'$1
grep 'WASHINGTON'                  $1 > 'WASHINGTON_'$1
grep 'WAYNE'                       $1 > 'WAYNE_'$1
grep 'WESTMORELAND'                $1 > 'WESTMORELAND_'$1
grep 'WYOMING'                     $1 > 'WYOMING_'$1
grep 'YORK'                        $1 > 'YORK_'$1